# Common config. It defines all configuration variables but it's not intended to be used
# directly.
common: &common
  asset_domain: gamersmafia.com
  asset_url: http://gamersmafia.com
  cache_templates_in_production: true
  compress_js?: true
  compress_skins?: true
  debug: false
  domain: gamersmafia.com
  domain_aliases:
    - 4americasarmy.com
    - 4coders.net
    - 4mohers.com
    - 4quakers.com
    - 4ragnarok.com
    - 4soldiers.net
    - 4unrealers.com
    - battlefieldspain.com
    - bf1942spain.com
    - d3-esp.com
    - defuseit.com
    - dowforever.com
    - quakereligion.com
    - sc2-esp.net
  domain_bazar: bazar.gamersmafia.com
  domain_arena: arena.gamersmafia.com
  enable_bgjobs?: false
  enable_dbstats?: false
  enable_google_analytics?: false
  enable_tidy?: true
  ia_auto_ab_tests: nagato
  ia_auto_abtests: MrAchmed
  log_env: development
  mirror_auth_key: secret
  port: 80
  python: /usr/local/hosting/bin/python2.4
  redis_db: 0
  session_secret: secretsecretsecretsecretsecret
  show_ads: false
  system_mail_domain: gamersmafia.com
  system_mail_host: imap.gmail.com
  system_mail_password: megustanlasgalletas
  system_mail_user: nagatodev@gamersmafia.com
  webmaster_email: unnamed@gamersmafia.dev
  webmaster_user_id: 41793
  weekly_internal_report_recipient: alerts@gamersmafia.com

# Basic roles.
development: &development
  <<: *common
  asset_domain: gamersmafia.dev
  asset_url: http://gamersmafia.dev
  cache_templates_in_production: false
  compress_js?: false
  compress_skins?: false
  debug: false
  domain: gamersmafia.dev
  domain_arena: arena.gamersmafia.dev
  domain_bazar: bazar.gamersmafia.dev
  enable_bgjobs?: false
  enable_dbstats?: true
  python: python

test: &test
  <<: *common
  asset_domain: test.host
  domain: test.host
  domain_bazar: bazar.test.host
  domain_arena: arena.test.host
  redis_db: 1
