log4r_config:
  # define all loggers ...
  loggers:
    - name      : production
      level     : WARN
      trace     : 'false'
      outputters :
      - datefile
    - name      : development
      level     : WARN
      trace     : 'true'
      outputters :
      - datefile
      - stdout
    - name      : test
      level     : WARN
      trace     : 'true'
      outputters :
      - datefile
      - stdout

  # define all outputters (incl. formatters)
  outputters:
  - type: DateFileOutputter
    name: datefile
    dirname: "log"
    file: "my_log" # this will be overrided by rails' config.
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '[%-5l] %d: %m '
      type        : PatternFormatter
  - type: StdoutOutputter
    name: stdout
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '[%-5l] %d: %m '
      type        : PatternFormatter
